env:
    DEVICE_CODENAME: vivo
    BUILD_USER: NFSproject
    BUILD_HOST: NFS86
    KERNEL_SOURCE: https://github.com/adomerle/linux-mt6765
    KERNEL_BRANCH: mt6765-next
    TOOLCHAIN_SOURCE: https://gitlab.com/ZyCromerZ/sdclang-16.0.2.0.git
    TOOLCHAIN_BRANCH: main
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: https://github.com/NFS-Project/AnyKernel3.git
    TG_TOKEN: 
    TG_CHAT_ID: 

task:
  name: "Kernel Build.."
  timeout_in: 120
  stateful: true
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./done.sh
